#!/usr/bin/env python3
"""Failure diagnostic report (post-TRIZ-42 NE-3 remediation).

Previously this script mined benchmark failures to **generate Rust snippets**
for ``crates/pure-reason-core/src/world_priors.rs``.  That pipeline was a
textbook test-set-fitting loop: run benchmark → read which items the
detector missed → add hand-crafted patterns that match those specific items
→ rerun and report higher F1.  The output is no longer suitable for code
generation and the Rust-snippet emitter has been removed.

What this script does now
-------------------------
It reads a failures JSON dump and produces a **markdown taxonomy report**
summarising the kinds of items the current detector misses (term and bigram
frequency, per-benchmark counts).  The output is intended to guide the
design of *external-corpus-derived* priors, not to be pasted into
``world_priors.rs``.

Populating ``world_priors.rs`` from the output of this script is forbidden.
CI enforces this via ``benchmarks/benchmark_leak_audit.py``, which fails the
build if any ``world_priors`` signal string appears in a benchmark's test
file.

Usage::

    python3 scripts/mine_failures.py \\
        --input benchmarks/results/failures_heuristic.json \\
        --output benchmarks/results/failure_taxonomy.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_FAILURES = REPO / "benchmarks" / "results" / "failures_heuristic.json"
DEFAULT_OUTPUT = REPO / "benchmarks" / "results" / "failure_taxonomy.md"


STOPWORDS = frozenset(
    {
        "that", "this", "with", "from", "have", "been", "they", "were", "will",
        "would", "could", "should", "than", "when", "what", "which", "their",
        "there", "these", "those", "some", "only", "just", "more", "also",
        "very", "most", "does", "such", "into", "about", "both", "each",
        "true", "false", "answer", "question", "context", "preview",
    }
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Emit a markdown taxonomy of benchmark failures. "
        "Does NOT generate code.",
    )
    parser.add_argument("--input", default=str(DEFAULT_FAILURES))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--min-freq", type=int, default=2)
    parser.add_argument("--top-n", type=int, default=30)
    return parser.parse_args()


def load_failures(path: Path) -> list[dict]:
    if not path.exists():
        raise SystemExit(f"Failures file not found: {path}")
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)

    failures: list[dict] = []
    if isinstance(data, list):
        for item in data:
            if item.get("ground_truth") and not item.get("predicted"):
                failures.append(item)
    elif isinstance(data, dict):
        for _bm_key, bm_data in data.items():
            if isinstance(bm_data, dict):
                for record in bm_data.get("failures", []) or []:
                    if record.get("ground_truth") and not record.get("predicted"):
                        failures.append(record)
    return failures


def extract_terms(text: str) -> list[str]:
    return [w for w in re.findall(r"[a-zA-Z]{4,}", text.lower()) if w not in STOPWORDS]


def main() -> int:
    args = parse_args()
    input_path = Path(args.input).resolve()
    output_path = Path(args.output).resolve()

    failures = load_failures(input_path)
    if not failures:
        print("No false-negative failures found; nothing to report.")
        return 0

    by_benchmark: Counter = Counter()
    all_terms: list[str] = []
    all_bigrams: Counter = Counter()

    for failure in failures:
        by_benchmark[failure.get("benchmark", "unknown")] += 1
        text = failure.get("text_preview", "") or ""
        terms = extract_terms(text)
        all_terms.extend(terms)
        for i in range(len(terms) - 1):
            all_bigrams[f"{terms[i]} {terms[i + 1]}"] += 1

    term_freq = Counter(all_terms)

    lines: list[str] = []
    lines.append("# Benchmark failure taxonomy\n")
    lines.append(
        "> Generated by `scripts/mine_failures.py`. This is a **diagnostic** "
        "report. Do NOT use it to author `world_priors.rs` entries "
        "(TRIZ-42 NE-3)."
    )
    lines.append(f"\nTotal missed hallucinations: **{len(failures)}**")
    lines.append("\n## Per-benchmark breakdown\n")
    for bench, count in by_benchmark.most_common():
        lines.append(f"- `{bench}`: {count}")

    lines.append(f"\n## Top {args.top_n} unigrams (frequency ≥ {args.min_freq})\n")
    for term, freq in term_freq.most_common(args.top_n):
        if freq < args.min_freq:
            break
        lines.append(f"- `{term}` — {freq}")

    lines.append(f"\n## Top {args.top_n} bigrams (frequency ≥ {args.min_freq})\n")
    for bigram, freq in all_bigrams.most_common(args.top_n):
        if freq < args.min_freq:
            break
        lines.append(f"- `{bigram}` — {freq}")

    lines.append("\n## How to act on this report\n")
    lines.append(
        "- Categorise the top terms/bigrams into *domains of weakness* "
        "(e.g. arithmetic, entity grounding, temporal, legal)."
    )
    lines.append(
        "- Look for **external** knowledge sources that cover each domain "
        "(Wikipedia, domain ontologies, structured KB)."
    )
    lines.append(
        "- Derive detector signals from those external sources — never from "
        "the benchmark CSV/JSONL itself."
    )
    lines.append(
        "- Run `python3 benchmarks/benchmark_leak_audit.py --verbose` "
        "before landing any change that touches `world_priors.rs`."
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote failure taxonomy → {output_path}")
    print(f"  {len(failures)} failures across {len(by_benchmark)} benchmark(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
